### PR TITLE
updated universes for sunstone and betanet

### PR DESCRIPTION
**Pull request by blenessy**
Generated from RadixCore @ 1dc442c5a728f0d48b976b37d36bd78414c381d8

### CODE REVIEW

**Comment by blenessy** [comment]
@laszlourszuly you might want to try using the sunstone2 branch with your xBT service & sunstone network.

**Comment by laszlourszuly** [comment]
> @laszlourszuly you might want to try using the sunstone2 branch with your xBT service & sunstone network.

Sweet! I'll try it out immediately!

**Comment by laszlourszuly** [comment]
@blenessy OK one step forward! I could successfully build and deploy the ABT service to remote host. I can reach the service and log in with pre-configured users.

But I'm not sure what happens then. I try to mint some tokens but exactly nothing happens ledger-wise. The web app suggests there is a minting in progress, but I don't see any activity at all on Prometheus, neither does the service print any logs. I'll look closer at this tomorrow (might be something service-related as I haven't tested with this version of the Java library yet)

**Comment by laszlourszuly** [comment]
@blenessy Just a heads-up when you rebase this PR: There is a new commit on `develop` now which seems to have a better Sunstone Universe config (please don't overwrite it): 1e8e549285ce90e5304efe3b5b6e54c48a3ff810

It doesn't have your other changes, though.

**Comment by laszlourszuly** [comment]
@blenessy Should this be merged? The ABT service currently relies on this version of the code (because of the BETANET universe it offers).

**Comment by blenessy** [comment]
yeah @laszlourszuly we need this merged but unfortunately it has conflicts and I can't spare the time right now.

**Comment by laszlourszuly** [comment]
@blenessy Do you mind if I give it a try?

**Comment by Sajjon** [comment]
Hmm how come the serializer values are integers, it looks like this branch contains the PR #181 which is RLAU-581 human readable serializers.  So shouldn't `betanet.json` and `localnet.json` contain human readable serializers than? 

Ping @blenessy

**Comment by blenessy** [comment]
@Sajjon  On `develop` betanet.json` is (when I created this PR) a test universe that has nothing to do with the real betanet configuration. That is why I want to move that stuff to `localnet.json` .

**Pull request merged**
