### PR TITLE
New Jackson-based serialization

### PR DESCRIPTION
**Pull request by mpsandiford**
For review.

### CODE REVIEW

**Comment by talekhinezh** [comment]
@mpsandiford `./gradlew build` fails for me locally with:
```
/radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
         *              for {@code i} &in; {@code [0, length1)}.
                                      ^
/radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
         * no bounds checking is performed on the incoming bytes &emdash;
```

**Comment by mpsandiford** [comment]
> @mpsandiford `./gradlew build` fails for me locally with:
> 
> ```
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
>          *              for {@code i} &in; {@code [0, length1)}.
>                                       ^
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
>          * no bounds checking is performed on the incoming bytes &emdash;
> ```

It looks like checkstyle doesn't like the (valid HTML) entities &in; and &emdash; for some reason.  I've replaced them with the Unicode hex equivalents, which frankly less readable in my opinion, but seems to placate checkstyle.

Also, there seems to be a difference between what checkstyle does when one runs `gradle check` and `gradle build` for some reason.  When running `gradle check` it appears that the checkstyle checks for javadoc are omitted.  Perhaps we should change Travis CI to do a `gradle build` rather than a `gradle check` as it currently does?

**Comment by mpsandiford** [comment]
> @mpsandiford `./gradlew build` fails for me locally with:
> 
> ```
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
>          *              for {@code i} &in; {@code [0, length1)}.
>                                       ^
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
>          * no bounds checking is performed on the incoming bytes &emdash;
> ```

It looks like checkstyle doesn't like the (valid HTML) entities &in; and &emdash; for some reason.  I've replaced them with the Unicode hex equivalents, which frankly less readable in my opinion, but seems to placate checkstyle.

Also, there seems to be a difference between what checkstyle does when one runs `gradle check` and `gradle build` for some reason.  When running `gradle check` it appears that the checkstyle checks for javadoc are omitted.  Perhaps we should change Travis CI to do a `gradle build` rather than a `gradle check` as it currently does?

**Comment by mpsandiford** [comment]
> @mpsandiford `./gradlew build` fails for me locally with:
> 
> ```
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
>          *              for {@code i} &in; {@code [0, length1)}.
>                                       ^
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
>          * no bounds checking is performed on the incoming bytes &emdash;
> ```

It looks like checkstyle doesn't like the (valid HTML) entities &in; and &emdash; for some reason.  I've replaced them with the Unicode hex equivalents, which frankly less readable in my opinion, but seems to placate checkstyle.

Also, there seems to be a difference between what checkstyle does when one runs `gradle check` and `gradle build` for some reason.  When running `gradle check` it appears that the checkstyle checks for javadoc are omitted.  Perhaps we should change Travis CI to do a `gradle build` rather than a `gradle check` as it currently does?

**Comment by mpsandiford** [comment]
> @mpsandiford `./gradlew build` fails for me locally with:
> 
> ```
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
>          *              for {@code i} &in; {@code [0, length1)}.
>                                       ^
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
>          * no bounds checking is performed on the incoming bytes &emdash;
> ```

It looks like checkstyle doesn't like the (valid) HTML entities \&in; and \&emdash; for some reason.  I've replaced them with the Unicode hex equivalents, which frankly less readable in my opinion, but seems to placate checkstyle.

Also, there seems to be a difference between what checkstyle does when one runs `gradle check` and `gradle build` for some reason.  When running `gradle check` it appears that the checkstyle checks for javadoc are omitted.  Perhaps we should change Travis CI to do a `gradle build` rather than a `gradle check` as it currently does?

**Comment by mpsandiford** [comment]
> @mpsandiford `./gradlew build` fails for me locally with:
> 
> ```
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
>          *              for {@code i} &in; {@code [0, length1)}.
>                                       ^
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
>          * no bounds checking is performed on the incoming bytes &emdash;
> ```

It looks like checkstyle doesn't like the (valid) HTML entities \&in; and \&emdash; for some reason.  I've replaced them with the Unicode hex equivalents, which frankly less readable in my opinion, but seems to placate checkstyle.

Also, there seems to be a difference between what checkstyle does when one runs `gradle check` and `gradle build` for some reason.  When running `gradle check` it appears that the checkstyle checks for javadoc are omitted.  Perhaps we should change Travis CI to do a `gradle build` rather than a `gradle check` as it currently does?

**Comment by mpsandiford** [comment]
> @mpsandiford `./gradlew build` fails for me locally with:
> 
> ```
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Bytes.java:29: error: invalid entity &in;
>          *              for {@code i} &in; {@code [0, length1)}.
>                                       ^
> /radixdlt-java/radixdlt-java/src/main/java/org/radix/utils/primitives/Strings.java:39: error: invalid entity &emdash;
>          * no bounds checking is performed on the incoming bytes &emdash;
> ```

It looks like checkstyle doesn't like the (valid) HTML entities \&in; and \&emdash; for some reason.  I've replaced them with the Unicode hex equivalents, which frankly less readable in my opinion, but seems to placate checkstyle.

Also, there seems to be a difference between what checkstyle does when one runs `gradle check` and `gradle build` for some reason.  When running `gradle check` it appears that the checkstyle checks for javadoc are omitted.  Perhaps we should change Travis CI to do a `gradle build` rather than a `gradle check` as it currently does?

**Comment by mpsandiford** [comment]
Not sure why this was closed? Reopening.

**Pull request merged**
